### ISSUE TITLE
How to use harness.py?

### ISSUE THREAD

**Issue by luoxuan-cs** [jacksoncooper/cmpsc-154-harnesses#2]
Great work! But I am wondering how to use the harness.py? 
I just add these two rows at the bottom of harness.py:

`test1 = TestAdd
TestAdd.test_add_different_operands_and_destination_is_not_operand`

However, when I run python harness.py, nothing happened.
Thanks for your help!

**Comment by luoxuan-cs** [comment]
I found that if I pass the test, there is no output.

**Comment by jacksoncooper** [comment]
I left directions in the Piazza post. Clone the repository, place your `cpu.py` in it and run `pytest --disable-warnings --verbose harness.py`. There should be _some_ output when you pass the tests. Mine looks like this.

```
...
harness.py::TestConsecutiveInstructions::test_lui_program PASSED                                             [ 93%]
harness.py::TestConsecutiveInstructions::test_all_consecutive_with_bad_host PASSED                           [ 96%]
harness.py::TestConsecutiveInstructions::test_all_consecutive_with_good_host PASSED                          [100%]

========================================== 31 passed, 1 warning in 0.77s ===========================================
```
